apiVersion: v1
kind: Service
metadata:
  name: configserver-clusterip
spec:
  selector:
    project: configserver
    app: configserver
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: configserver-nodeport
spec:
  type: NodePort
  selector:
    project: configserver
    app: configserver
  ports:
   - protocol: TCP
     port: 8888
     targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  labels:
    project: configserver
    app: configserver
spec:
  minReadySeconds: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
  replicas: 6
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
     containers:
     - name: appconfig
       image: pcspam/app-config
       ports:
        - containerPort: 8888


        