apiVersion: v1
kind: ReplicationController
metadata:
  name: configserver-RC
spec:
  replicas: 2
  selector:
    project: configserver
    service: web
    version: "0.1"
  template:
    metadata:
      name: nginx
      labels:
       project: configserver
       service: web
       version: "0.1"
    spec:
     containers:
      - name: nginx
        image: nginx:1.12.0
        ports:
          - containerPort: 80
