apiVersion: v1
kind: Service
metadata:
  name: configserver-nodeport
spec:
  type: NodePort
  selector:
    project: configserver
    service: web
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80