apiVersion: v1
kind: Service
metadata:
  name: invoiceserver-loadbalancer
spec:
  type: LoadBalancer
  selector:
    project: invoiceserver
    service: web
  ports:
   - port: 8765
     targetPort: 9376

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoiceserver-deployment
  labels:
   app: invoiceserver
spec:
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
  replicas: 2
  selector:
    matchLabels:
         app: invoiceserver
  template:
    metadata:
      labels:
        app: invoiceserver
    spec:
     containers:
     - name: appinvoice
       image: icesiops/appinvoice:0.1.0
       ports:
        - containerPort: 8006